### ISSUE TITLE
Please add the following papers

### ISSUE THREAD

**Issue by mistake0316** [yzhuoning/Awesome-CLIP#1]
[Text2Mesh](https://threedle.github.io/text2mesh/) : Their approach can modify a given mesh with given text/image information via CLIP text/image encoder.

[Detecting Twenty-thousand Classes using Image-level Supervision](https://github.com/facebookresearch/Detic) : Which is a object detection research by facebook, they use CLIP  text embedding as classifier weight.

The above papers are I want to add.

----

I think Crop-CLIP should be put at *Object Detection*

----
For more *image manipuliation / generation* applications, I summarized in my medium
You can add them if you think they are valueable.
[Text-Driven Image Manipulation/Generation with CLIP](https://medium.com/p/d16568f7c16f)
![CLIP image genration Applications](https://miro.medium.com/max/1400/1*KyR8TnRhtEkkXJMCGvcFIQ.png)
The list of above image is allocated at this google [sheet](https://docs.google.com/spreadsheets/d/1tlt2Kb2UkjCvdvNaJiEw_TcqtePQJ1RXfpe3m9OCr-M/edit#gid=0)

**Comment by yzhuoning** [comment]
Thanks for your input! I have included the above two papers. I will check your list later.
