### ISSUE TITLE
related work on information retrieval

### ISSUE THREAD

**Issue by mariyahendriksen** [yzhuoning/Awesome-CLIP#10]
Hello!

Thanks for creating this repository, it is super useful!

My colleagues and I recently finalized the work on using CLIP for information retrieval in e-commerce domain. The paper is called 'Extending CLIP for Category-to-image Retrieval in E-commerce', we presented it on ECIR 2022 a couple of month ago.
I would really appreciate it if you could add it to the Information Retrieval subsection. Here is the markdown code in case it is helpful:

- Extending CLIP for Category-to-image Retrieval in E-commerce [[paper](https://arxiv.org/abs/2112.11294)]

Please let me know if you'd rather me send a pull request.

Thank you!

**Comment by yzhuoning** [comment]
Hi, I have included your paper & code in this update. Thanks!

**Comment by mariyahendriksen** [comment]
thanks!
