### ISSUE TITLE
Adding CLIP-as-service?

### ISSUE THREAD

**Issue by hanxiao** [yzhuoning/Awesome-CLIP#2]
CLIP-as-service is a low-latency high-scalability service for embedding images and text. It can be easily integrated as a microservice into neural search solutions.

Code: https://github.com/jina-ai/clip-as-service
Docs: https://clip-as-service.jina.ai/

Would be awesome to add to this awesome list! Thanks in advance!

**Comment by yzhuoning** [comment]
Great work! I have included it in the list. Thanks!
