### ISSUE TITLE
（CVPR 2022）Please consider our weakly supervised semantic segmentation based on CLIP

### ISSUE THREAD

**Issue by Sierkinhane** [yzhuoning/Awesome-CLIP#4]
CLIMS: Cross Language Image Matching for Weakly Supervised Semantic Segmentation
Paper: https://arxiv.org/abs/2203.02668
Code: https://github.com/CVI-SZU/CLIMS

**Comment by yzhuoning** [comment]
Thanks for the input. I have included your paper!
