### ISSUE TITLE
Maybe add these papers related to few-shot image classification?

### ISSUE THREAD

**Issue by tingxueronghua** [yzhuoning/Awesome-CLIP#5]
- Learning to Prompt for Vision-Language Models [[paper](https://arxiv.org/abs/2109.01134.pdf)][[code](https://github.com/KaiyangZhou/CoOp)]
- Conditional Prompt Learning for Vision-Language Models [[paper](https://arxiv.org/abs/2203.05557.pdf)][[code](https://github.com/KaiyangZhou/CoOp)]
- Prompt-aligned Gradient for Prompt Tuning [[paper](https://arxiv.org/abs/2205.14865.pdf)][[code](https://github.com/BeierZhu/Prompt-align)]
- CLIP-Adapter: Better Vision-Language Models with Feature Adapters [[paper](https://arxiv.org/abs/2110.04544.pdf)][[code](https://github.com/gaopengcuhk/CLIP-Adapter)]

**Comment by yzhuoning** [comment]
I have included these papers. Thanks for your inputs!
