### ISSUE TITLE
The code of RegionCLIP is now public

### ISSUE THREAD

**Issue by YiwuZhong** [yzhuoning/Awesome-CLIP#7]
Hi Zhuoning,

Thanks for your contribution for this nice repo!

Just wanted to give a update that our work RegionCLIP (CVPR 2022) is now public (https://github.com/microsoft/RegionCLIP). Feel free to give it a try!

PS: the name of RegionCLIP was misspelled.

Best,
Yiwu

**Comment by yzhuoning** [comment]
Hi Yiwu, great work! I have fixed the typo and included the code link.
