### ISSUE TITLE
Related work on prompt learning

### ISSUE THREAD

**Issue by nihalnayak** [yzhuoning/Awesome-CLIP#8]
Hi! 

This is an excellent collection of CLIP-related works. We recently put out a preprint on prompt learning. It would be awesome if you could include our work under the Prompt Learning section. Below are the details: 

- Learning to Compose Soft Prompts for Compositional Zero-Shot Learning [[paper](https://arxiv.org/abs/2204.03574)] [[code](https://github.com/BatsResearch/csp)]

Please let me know if you want me to send a PR instead. 

Thank you!

**Comment by yzhuoning** [comment]
Hi, I have included your paper & code in this update. Thanks!
